name: Deploy and Test Code Base
on: push

jobs:
  test_code:
    runs-on: ubuntu-latest
    steps:
      - name: Download the Repo
        uses: actions/checkout@v3
      - name: Investigate the Environment
        run: |
          pwd
          ls -lart