name: Output Info Demo
on: 
  pull_request:
    branches:
      main
  push: 
    branches:
      new_branch
  workflow_dispatch:

jobs:
  display_info:
    runs-on: ubuntu-latest
    steps:
      - name: Show Some Info
        run: echo "${{ toJSON(github) }}"