name: Output Info Demo
on: 
  push: 
    branches:
      - main
      - new_branch
    paths-ignore:
      - '.github'


jobs:
  display_info:
    runs-on: ubuntu-latest
    steps:
      - name: Show Some Info
        run: echo "${{ toJSON(github) }}"